### ISSUE TITLE
Having both /etc/X11/Xsession.d/99mate-environment and /etc/X11/Xsession.d/80mate-environment break Caja-DropBox after upgrade from Ubuntu 16.04 LTS to 18.04 LTS

### ISSUE THREAD

**Issue by N0rbert** [ubuntu-mate/ubuntu-mate-settings#3]
**Steps to reproduce:**
1. Have Ubuntu 16.04.5 LTS with `ubuntu-mate-desktop` and `caja-dropbox` installed
2. Upgrade it with `do-release-upgrade -d` to 18.04.1 LTS
3. Reboot after upgrade to new system, login and get no Dropbox icon in the tray.
4. Remove DropBox from the system (as in https://ubuntu-mate.community/t/problems-with-the-dropbox-icon-in-the-panel-um-18-04-1/17495/6 ):

```
killall dropbox
sudo apt-get purge caja-dropbox
rm -rf ~/.dropbox
sudo apt-get install caja-dropbox
````

5. Reboot and log-in again, still no DropBox icon.
6. Try to launch DropBox from terminal with `caja-dropbox start` and get the following output in the terminal (as in https://ubuntu-mate.community/t/problems-with-the-dropbox-icon-in-the-panel-um-18-04-1/17495/7):

```
$ caja-dropbox start
...
Gtk-Message: 15:44:51.977: Failed to load module "topmenu-gtk-module"
...
```

**Expected results:** `caja-dropbox` works after upgrading from 16.04.5 LTS to 18.04.1 LTS.

**Actual results:** `caja-dropbox` does not work after upgrading from 16.04.5 LTS to 18.04.1 LTS.

The **solution** is to remove one file 

    sudo rm /etc/X11/Xsession.d/99mate-environment

as it contain references to non-existent `topmenu-gtk-module` - see below

```
$ sudo grep -ir topmenu-gtk-module /etc/
/etc/X11/Xsession.d/99mate-environment:        GTK_MODULES="canberra-gtk-module:topmenu-gtk-module"
/etc/X11/Xsession.d/99mate-environment:        GTK_MODULES="$GTK_MODULES:canberra-gtk-module:topmenu-gtk-module"
```

and then reboot.

**Downstream report** : [bug 1785622 at LaunchPad](https://bugs.launchpad.net/ubuntu/+source/caja-dropbox/+bug/1785622).

**Recommendation:** consider removing this file during upgrade of [`ubuntu-mate-default-settings` package](https://packages.ubuntu.com/bionic/amd64/ubuntu-mate-default-settings/filelist) or rename it back to [`/etc/X11/Xsession.d/99mate-environment` as it was in 16.04 LTS](https://packages.ubuntu.com/xenial/amd64/ubuntu-mate-default-settings/filelist) to make `do-release-upgrade`-process smoother.

**Comment by vkareh** [comment]
@flexiondotorg - Seems like [this line](https://github.com/ubuntu-mate/ubuntu-mate-settings/blob/8c75bfbc1f9b3bf7cb28a3633f5237bff30eb1fa/debian/ubuntu-mate-default-settings.maintscript#L9) may need the version number dropped so that it applies to any upgrade path, as LTS upgrades skip versions:
```
rm_conffile /etc/X11/Xsession.d/99mate-environment 17.10.17
```
I could make this change, however I'm not entirely sure how to test this yet...

**Comment by N0rbert** [comment]
MATE Dictionary seems to be affected by this setting file (see this [Q&A on AskUbuntu](https://askubuntu.com/q/1132560/66509) ) and other simple apps complain:

```
$ mate-calc
Gtk-Message: 11:15:39.978: Failed to load module "topmenu-gtk-module"
$ mate-about
Gtk-Message: 11:16:15.685: Failed to load module "topmenu-gtk-module"
$ mate-appearance-properties 
Gtk-Message: 11:16:31.356: Failed to load module "topmenu-gtk-module"
$ mate-color-select 
Gtk-Message: 11:16:51.928: Failed to load module "topmenu-gtk-module"
...
$ mate-window-properties 
Gtk-Message: 11:17:08.009: Failed to load module "topmenu-gtk-module"
```
Maybe SRU for `ubuntu-mate-default-settings` in 18.04 LTS is required to prevent such messages problems on systems upgraded from 16.04 LTS.
