### ISSUE TITLE
General Question: Plank / MATE Panel Settings for Mutiny

### ISSUE THREAD

**Issue by chaibronz** [ubuntu-mate/ubuntu-mate-settings#6]
First just want to apologize that I don't know where else to post this, but wondering how you configure plank and the MATE panel to 'not' overlap each other in the Mutiny layout.  By default, adding a Plank panel in 'Fill' mode will fill the screen end to end, hence overlap with any existing panels in the way.  In Mutiny, it's somehow configured to account for the space that the top panel takes up.  I can't find an obvious setting for this or any information about this online, so wondering how you create that magical 'offset' in Plank?

**Comment by flexiondotorg** [comment]
See https://github.com/ubuntu-mate/mate-tweak for how Plank is configured to the Mutiny layout.

- https://github.com/ubuntu-mate/mate-tweak/blob/master/mate-tweak#L848
